#!/bin/sh

set -e

KEY_URL="http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key"

/bin/route add -net 169.254.0.0/16 dev eth0
block-until-url "$KEY_URL"
curl --fail -s "$KEY_URL" | update-ssh-keys -a ec2
